version: '3.9'

services:
  db:
    image: postgres:14.4-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    env_file:
      - .env
    volumes:
      - resume-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - resume-network
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    restart: always
    hostname: resume-backend
    depends_on:
      - db
    ports:
      - '8001:8001'
    env_file:
      - .env
    networks:
      - resume-network
volumes:
  resume-data:
networks:
  resume-network: